eval %sh{kak-lsp --kakoune -s $kak_session -c ~/.config/kak-lsp/kak-lsp.toml}  # Not needed if you load it with plug.kak.
lsp-enable

hook global WinSetOption filetype=rust %{
    hook window -group rust-inlay-hints BufReload .* rust-analyzer-inlay-hints
    hook window -group rust-inlay-hints NormalIdle .* rust-analyzer-inlay-hints
    hook window -group rust-inlay-hints InsertIdle .* rust-analyzer-inlay-hints
    hook -once -always window WinSetOption filetype=.* %{
            remove-hooks window rust-inlay-hints
    }
}

set tabstop 4
set indentwidth 4

map global user l %{: enter-user-mode lsp<ret>} -docstring "LSP mode"
map global insert { {<ret><ret>}<up><tab>
map global normal ( *hni(<esc>a)<esc>

add-highlighter global/ wrap -word -indent
add-highlighter global/ number-lines -relative
set-option global scrolloff 15,40
