theme = "onedark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"
B = "extend_prev_word_start"
W = "extend_next_word_start"
E = "extend_next_word_end"
"C-j" = "join_selections" 

[keys.normal.space.l]
e = "goto_next_diag"
E = "goto_prev_diag"